name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --frozen-lockfile
      - name: Deploy
        run: yarn gh-pages -d build -x -r https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          NODE_DEBUG: gh-pages
