name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --frozen-lockfile
      - name: Deploy
        run: yarn run deploy
        env:
          NODE_DEBUG: gh-pages
