name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --frozen-lockfile
      - name: Git configuration
        run: |
          git config --global user.email "luchansodev@gmail.com"
          git config --global user.name "github-actions-ci"
      - name: Deploy
        run: yarn run deploy
        env:
          NODE_DEBUG: gh-pages
